spring.application.name=crud-imagem
spring.profiles.active=prod
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://localhost:3306/WeGo
spring.datasource.username=root
spring.datasource.password=Fe11018\@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

logging.level.org.springframework=DEBUG
logging.level.org.springframework.security=INFO
logging.config=classpath:log4j2.xml

app.image.storage.path=c:/temp/imagens

app.email.from.address=suportepetinder360@gmail.com
app.email.from.name=Equipe PeTinder
app.email.smtp.host=smtp.gmail.com
app.email.smtp.port=587
app.email.smtp.username=${app.email.from.address}
#app.email.smtp.password=${SENHA_PETINDER_EMAIL}
app.email.smtp.password=sisbuzmbuvlfwlxc

spring.mail.host=${app.email.smtp.host}
spring.mail.port=${app.email.smtp.port}
spring.mail.username=${app.email.smtp.username}
spring.mail.password=${app.email.smtp.password}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=${app.email.smtp.host}
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000


jwt.secret=RXhpc3RlIHVtYSB0ZW9yaWEgcXVlIGRpeiBxdWUsIHNlIHVtIGRpYSBhbGd16W0gZGVzY29icmlyIGV4YXRhbWVudGUgcGFyYSBxdWUgc2VydmUgbyBVbml2ZXJzbyBlIHBvciBxdWUgZWxlIGVzdOEgYXF1aSwgZWxlIGRlc2FwYXJlY2Vy4SBpbnN0YW50YW5lYW1lbnRlIGUgc2Vy4SBzdWJzdGl0de1kbyBwb3IgYWxnbyBhaW5kYSBtYWlzIGVzdHJhbmhvIGUgaW5leHBsaWPhdmVsLiBFeGlzdGUgdW1hIHNlZ3VuZGEgdGVvcmlhIHF1ZSBkaXogcXVlIGlzc28gauEgYWNvbnRlY2V1Li4u
jwt.validity=3600000

logFolder=${user.home}/Desktop/S3 local/logs

aws_access_key_id=ASIAQKODERJZ4IAXQCLJ
aws_secret_access_key=zxlvgJpe00fcmq6dwocFIfo1hSp5xB4KnUvzSNgP
aws_session_token=IQoJb3JpZ2luX2VjEHgaCXVzLXdlc3QtMiJHMEUCICLE6bjRCcb/KckLQtRI1wThROiuI6Y8eN7eRF3VL1hLAiEArkYnBwG3OXbPvUa789uERJF4aULr/2s3wSJ1658jHPYqtQIIQRAAGgwwMjI0MjA5NDk2MTkiDHB47HAkgrHlmVCMIiqSAuKdX8o+bgSW4sp8dtJkLlVoYqPIAwTg7yTiF2oQud5whWRxcEu0QmupCEbRElqV27c3OZL7/5S+MDyYvzr383aMvck38bpwbRnZbSy2+Wi4NESES3cQCo8wJSFepBvB5rKSNq6/6IzKPtppjvO4C9e1egKxi1Q6iPuBSuqkcY0N1PH5VDwChuYCVWwLdxVIMKuMMDsL2QHSz9DNVWQcij0z4rZDZ2ExCzpogBfOaghakUdJJWeWUWZV81WC6z+g8PMzQBLqNPg3a45tGyOH7gj4ku5UGEhq6nhmYrwQ4CVkE3vXwvscje6eVcmeij50LxiChdUIzIom65HxXPQNAt7AtMv250BkFzMCrlY6EwH29J8w9b3UyAY6nQHj5RUdDG4mLGOV7HszgaVELCnQ5V896Bnj3jRL8MsyOk5ELdzn7kUK4zg+L865Ml1cQNzIBPhTGNy2UVOx9POlmYaXdGJ4ZSDBlgroxsQObLl0pO04NVI4yiyNAsVSpkoDHYuIfmBQQxAqgckFGKO2ZtzkRO8oV7OHbh56zgi/hlC7ZGVaomOntXK2kxUbw0EwjxtCLlvjZeUeN4tz
aws.region.static=us-east-1
aws.s3.bucket=petinder-bucket
app.storage.type=s3